### ISSUE TITLE
Tracking number of member on discord 

### ISSUE THREAD

**Issue by Drlanderf** [Drlanderf/clara_oswald#129]
- [x] Track the current number of user in the discord server inside a channel
- [x] Add a field in the DB 
- [ ] Add the possibility to manual setting up with the slashcommand
- [ ] Add a new slashcommand to manually update the number of user in the guild
- [ ] try track who invite who
